# Generated by Django 6.0 on 2025-12-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='event_materials/'),
        ),
    ]
